name: tp-gerencia-configuracao-CI-CD-pipeline

on:
  push: 
    branches: ["main"]
  workflow_dispatch:

jobs:
  COMMIT:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Maven
        working-directory: ./api-pacientes
        run: mvn clean install
      - name: Run Unit and Integration Tests
        working-directory: ./api-pacientes
        run: mvn test
      - name: Run Acceptance Tests
        working-directory: ./api-pacientes
        run: mvn test -Dtest=CucumberRunner
