name: tp-gerencia-configuracao-CI-CD-pipeline

on:
  push: 
    branches: ["main"]
  workflow_dispatch:

jobs:
  COMMIT:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Maven
        working-directory: ./api-pacientes
        run: mvn clean install
      - name: Run Unit and Integration Tests
        working-directory: ./api-pacientes
        run: mvn test
  ACCEPTANCE:
    runs-on: ubuntu-latest
    needs: COMMIT
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Acceptance Tests
        working-directory: ./api-pacientes
        run: mvn test -Dtest=CucumberRunner
  PRODUCTION:
    runs-on: ubuntu-latest
    needs: [COMMIT, ACCEPTANCE]
    steps:
      - name: Get Code
        uses: actions/checkout@v4.1.3
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./api-pacientes
          file: ./api-pacientes/Dockerfile
          push: true
          tags: |
            gabriellimadesouza/tp-gerencia-configuracao:${{ github.sha }}
            gabriellimadesouza/tp-gerencia-configuracao:latest
